# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c8be52ccdf8c6bac84a61779331c0031099170414ea73735a04dc726bfc045878421870a0d1a3de3cea9a76724c2dbc6b3d6171ba3eb7a7438d8c5c677bb1bd

test:
  secret_key_base: 8ded7837777a6a9653c5ec1e99010a317673eb9e3dc9b7d42c1c2eeab7439a4a04b3ef0a7cd1b41a7ba6795071d5aa8e2b1fba60613faa9b02740848eb201455

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
